name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD      

    - name: Build the Docker image
      run: docker build -t hanseu9839/front .
    
    - name: taging
      run: docker tag hanseu9839/front:latest hanseu9839/front:latest
    
    - name: Push to Dockerhub
      run: docker push hanseu9839/front:latest
    
    - name: Deploy to server
      uses: fifsky/ssh-action@master
      id: deploy
      env:
        APP: "front"
        COMPOSE: "home/capo_project/docker-compose.yml"
      with:
        command: |
          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          sudo docker pull ${{secrets.DOCKER_REPO}}/front
          sudo docker-compose -f $COMPOSE up -d
        host: ${{secrets.HOST}}
        user: ${{secrets.USERNAME}}
        key: ${{secrets.KEY}}
